package com.firebaselibrary.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.firebaselibrary.bean.AreaBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "AREA_BEAN".
*/
public class AreaBeanDao extends AbstractDao<AreaBean, Long> {

    public static final String TABLENAME = "AREA_BEAN";

    /**
     * Properties of entity AreaBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Code = new Property(0, long.class, "code", true, "_id");
        public final static Property Value = new Property(1, String.class, "value", false, "VALUE");
    }


    public AreaBeanDao(DaoConfig config) {
        super(config);
    }
    
    public AreaBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"AREA_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: code
                "\"VALUE\" TEXT);"); // 1: value
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"AREA_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AreaBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getCode());
 
        String value = entity.getValue();
        if (value != null) {
            stmt.bindString(2, value);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AreaBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getCode());
 
        String value = entity.getValue();
        if (value != null) {
            stmt.bindString(2, value);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public AreaBean readEntity(Cursor cursor, int offset) {
        AreaBean entity = new AreaBean( //
            cursor.getLong(offset + 0), // code
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // value
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AreaBean entity, int offset) {
        entity.setCode(cursor.getLong(offset + 0));
        entity.setValue(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AreaBean entity, long rowId) {
        entity.setCode(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AreaBean entity) {
        if(entity != null) {
            return entity.getCode();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AreaBean entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
