package com.firebaselibrary.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.firebaselibrary.bean.NavigationHistoryBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NAVIGATION_HISTORY_BEAN".
*/
public class NavigationHistoryBeanDao extends AbstractDao<NavigationHistoryBean, Long> {

    public static final String TABLENAME = "NAVIGATION_HISTORY_BEAN";

    /**
     * Properties of entity NavigationHistoryBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Histroyid = new Property(0, Long.class, "histroyid", true, "_id");
    }


    public NavigationHistoryBeanDao(DaoConfig config) {
        super(config);
    }
    
    public NavigationHistoryBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NAVIGATION_HISTORY_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY );"); // 0: histroyid
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NAVIGATION_HISTORY_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, NavigationHistoryBean entity) {
        stmt.clearBindings();
 
        Long histroyid = entity.getHistroyid();
        if (histroyid != null) {
            stmt.bindLong(1, histroyid);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, NavigationHistoryBean entity) {
        stmt.clearBindings();
 
        Long histroyid = entity.getHistroyid();
        if (histroyid != null) {
            stmt.bindLong(1, histroyid);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public NavigationHistoryBean readEntity(Cursor cursor, int offset) {
        NavigationHistoryBean entity = new NavigationHistoryBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0) // histroyid
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, NavigationHistoryBean entity, int offset) {
        entity.setHistroyid(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(NavigationHistoryBean entity, long rowId) {
        entity.setHistroyid(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(NavigationHistoryBean entity) {
        if(entity != null) {
            return entity.getHistroyid();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(NavigationHistoryBean entity) {
        return entity.getHistroyid() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
